---
collections:
  - name: amazon.aws
  - name: ansible.posix
  - name: ansible.windows
  - name: awx.awx
  - name: azure.azcollection
  - name: community.docker
  - name: community.vmware
  - name: containers.podman
  - name: google.cloud
  - name: kubernetes.core
  - name: openstack.cloud
  - name: ovirt.ovirt
  - name: redhatinsights.insights
  - name: theforeman.foreman
