---
- name: configure pi-hole FTL
  template:
    src: etc/pihole/pihole-FTL.conf.j2
    dest: /etc/pihole/pihole-FTL.conf
    mode: 0644
  notify:
    - Restart pihole-FTL
  tags:
    - pihole
    - configure

- name: configure pi-hole local DNS records
  template:
    src: etc/pihole/custom.list.j2
    dest: /etc/pihole/custom.list
    mode: 0644
  when: pi_hole_local_dns_records is defined and pi_hole_local_dns_records | length > 0
  tags:
    - pihole
    - configure
