---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint: |
  set -e
  ansible-lint -q .

platforms:
  - name: "instance"
    image: "$image:$version"
    command: /sbin/init
    privileged: true
    env:
      - container: docker
    groups:
      - "default"

provisioner:
  log: true
  name: ansible
  inventory:
    links:
      group_vars: group_vars/
      host_vars: host_vars/
  playbooks:
    # create: create.yml
    # prepare: prepare.yml
    converge: ../resources/playbook.yml
  options:
    vvv: true
    dif: true

scenario:
  name: default
  # test_sequence:
  #   - destroy
  #   - dependency
  #   - syntax
  #   - create
  #   - prepare
  #   - converge
  #   - idempotence
    # - side_effect
    # - verify
    # - destroy

verifier:
  name: testinfra
