---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
    requirements-file: molecule/resources/requirements.yml

driver:
  name: docker

lint: |
  set -e
  ansible-lint -q .

platforms:
  - name: "instance"
    image: "$image:$version"
    command: /sbin/init
    privileged: true
    groups:
      - "default"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  log: true
  name: ansible
  inventory:
    links:
      group_vars: group_vars/
      host_vars: host_vars/
  playbooks:
    # create: create.yml
    # prepare: prepare.yml
    converge: ../resources/playbook.yml
  options:
    vvv: true
    dif: true

scenario:
  name: default

verifier:
  name: ansible
  enabled: False
