name: linter

on:
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/ansible/creator-ee:v0.4.2
      env:
        image: ubuntu
        version: 20.04
    steps:
      - uses: actions/checkout@v2
      - name: molecule lint
        run: |
          molecule lint
