name: linter

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    container:
      image: quay.io/ansible/toolset:3.5.0
      env:
        image: ubuntu
        version: 20.04
      # volumes:
      #   - /var/run/docker.sock:/var/run/docker.sock
      # options: --volume ${{ github.workspace }}:/tmp/${{ github.workspace }}:Z --workdir /tmp/${{ github.workspace }}
    steps:
      - uses: actions/checkout@v2
      - name: molecule lint
        run: |
          molecule lint
