name: linter

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: molecule lint
        run: |
          docker run --rm -it \
          --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD") \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -w /tmp/$(basename "$PWD") \
          quay.io/ansible/toolset:3.5.0 \
          molecule lint
