name: linter

on:
  pull_request:

jobs:
  checkout:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
  lint:
    runs-on: ubuntu-20.04
    needs: checkout
    container:
      image: quay.io/ansible/toolset:3.5.0
      env:
        image: ubuntu
        version: 20.04
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${{ github.workspace }}:/tmp/${{ github.workspace }}
      options: --workdir /tmp/${{ github.workspace }}
    steps:
      - name: molecule lint
        run: |
          molecule lint

    # run: |
    #   docker run --rm \
    #   --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD") \
    #   -v /var/run/docker.sock:/var/run/docker.sock \
    #   -w /tmp/$(basename "$PWD") \
    #   quay.io/ansible/toolset:3.5.0 \
    #   molecule lint
