name: molecule

on:
  pull_request:
    paths:
      - .github/molecule.yaml
      - "!.github/**"
      - "**"
  push:
    branches:
      - master

jobs:
  test:
    name: molecule test on ${{ matrix.image }} ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ubuntu
            version: "20.04"
          - image: ubuntu
            version: "22.04"
          - image: debian
            version: "10"
          - image: debian
            version: "11"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule molecule-plugins[docker] ansible-lint yamllint
      - name: molecule test
        env:
          image: ${{ matrix.image }}
          version: ${{ matrix.version }}
        run: |
          molecule test
