name: test

on:
  pull_request: {}

jobs:
  test:
    name: molecule test on ${{ matrix.image }} ${{ matrix.version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu
          - debian
          - fedora
          - centos
        include:
          - image: ubuntu
            version:
              - "18.04"
              - "20.04"
              - "21.10"
          - image: debian
            version:
              - "9"
              - "10"
              - "11"
          - image: fedora
            version:
              - "33"
              - "34"
          - image: centos
            version:
              - "7"
              - "8"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule["docker"] ansible-lint yamllint
      - name: molecule test
        env:
          image: ${{ matrix.image }}
          version: ${{ matrix.version }}
        run: |
          molecule test
