name: test

on:
  pull_request: {}

jobs:
  test:
    name: molecule test on ${{ matrix.image }} ${{ matrix.version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu
        version:
          - 18.04
          - 20.04
          - 21.10
          - 22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule["docker"] ansible-lint yamllint
      - name: molecule test
        run: |
          molecule test
