name: test

on:
  pull_request: {}

jobs:
  test:
    name: molecule test on ${{ matrix.image }} ${{ matrix.version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu
        version:
          - 18.04
          - 20.04
          - 21.10
          - 22.04
    container:
      image: quay.io/ansible/creator-ee:v0.4.2
      env:
        image: ${{ matrix.image }}
        version: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: molecule test
        run: |
          molecule test
